import asyncio
import logging
from aiogram import Bot, Dispatcher, types
from aiogram.filters import CommandStart, Command
from aiogram.enums import ParseMode
from aiogram.client.default import DefaultBotProperties
from aiogram.utils.markdown import hbold
from aiogram.types import BufferedInputFile
import aiohttp
import urllib.parse

import config
from database import db
from ai_manager import ai

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize bot and dispatcher
bot = Bot(token=config.BOT_TOKEN, default=DefaultBotProperties(parse_mode=ParseMode.MARKDOWN_V2))
dp = Dispatcher()

# Bot Commands
@dp.message(CommandStart())
async def command_start_handler(message: types.Message) -> None:
    user = message.from_user
    # Add user to database tracking
    await db.add_user(user.id, user.username, user.first_name)
    
    welcome_text = (
        f"Hello {hbold(user.first_name)}! 👋\n\n"
        "I am your Pro-Level AI Assistant. I can help you with coding, writing, research, and more!\n"
        "Just ask me anything to get started.\n\n"
        "/clear - Clear your conversational context/history"
    )
    # Simple escape for markdown v2
    welcome_text = welcome_text.replace('.', '\\.').replace('!', '\\!').replace('-', '\\-')
    await message.answer(welcome_text)

@dp.message(Command("image"))
async def image_generator_handler(message: types.Message):
    user_id = message.from_user.id
    
    # Check if user is banned
    user_db = await db.get_user(user_id)
    if user_db and user_db.get("banned", False):
        return

    # User format: /image <prompt>
    command_parts = message.text.split(" ", 1)
    if len(command_parts) < 2:
        await message.answer("Please provide a prompt to generate an image\\.\nExample: `/image a futuristic city`")
        return

    prompt = command_parts[1].strip()
    if not prompt:
        await message.answer("Please provide a prompt to generate an image\\.\nExample: `/image a flying horse`")
        return

    # Send 'uploading photo' action
    await bot.send_chat_action(chat_id=message.chat.id, action="upload_photo")
    status_msg = await message.answer("🎨 Generating your image\\.\\.\\.")

    # Generate Image using Pollinations AI (Free API, no key needed)
    try:
        encoded_prompt = urllib.parse.quote(prompt)
        # Using a fixed seed for better quality or random by default in API, adding specific instructions for better results
        url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&nologo=true"
        
        async with aiohttp.ClientSession() as session:
            async with session.get(url) as response:
                if response.status == 200:
                    image_data = await response.read()
                    photo = BufferedInputFile(image_data, filename="generated_image.png")
                    
                    caption = f"🎨 *Prompt:* {prompt}\n✨ *Generated by AI*"
                    caption = caption.replace('.', '\\.').replace('-', '\\!')
                    
                    await bot.send_photo(chat_id=message.chat.id, photo=photo, caption=caption)
                    await bot.delete_message(chat_id=message.chat.id, message_id=status_msg.message_id)
                    
                    # Log generation to history (optional, currently logging as user command)
                    await db.add_message(user_id, "user", f"/image {prompt}")
                    await db.inc_message_count(user_id)
                else:
                    await bot.edit_message_text("❌ Failed to generate image\\. Please try again later\\.", chat_id=message.chat.id, message_id=status_msg.message_id)
    except Exception as e:
        logger.error(f"Image generation error: {e}")
        await bot.edit_message_text("❌ An error occurred while generating the image\\.", chat_id=message.chat.id, message_id=status_msg.message_id)

@dp.message(Command("clear"))
async def clear_history_handler(message: types.Message):
    await db.clear_history(message.from_user.id)
    await message.answer("Your conversation memory has been cleared\\. We can start fresh\\!")

@dp.message(Command("stats"))
async def stats_handler(message: types.Message):
    if message.from_user.id == config.ADMIN_ID:
        users_count = await db.get_all_users_count()
        await message.answer(f"Bot Statistics:\nTotal Users: {users_count}")
    else:
        await message.answer("You are not authorized to use this command\\.")

@dp.message()
async def generic_message_handler(message: types.Message) -> None:
    user_id = message.from_user.id
    
    # Check if user is banned
    user_db = await db.get_user(user_id)
    if user_db and user_db.get("banned", False):
        return

    # Tracking user text
    user_text = message.text
    if not user_text:
        await message.answer("I only understand text messages for now\\.")
        return

    # Send typing action to show bot is 'thinking'
    await bot.send_chat_action(chat_id=message.chat.id, action="typing")

    # Get user history and format for Gemini
    history = await db.get_history(user_id)
    
    try:
        # Get AI Response
        response = await ai.generate_response(user_text, history)
        
        # Save both messages to history
        await db.add_message(user_id, "user", user_text)
        await db.add_message(user_id, "bot", response)
        await db.inc_message_count(user_id)
        
        # Send response safely - fallback to HTML or plain if Markdown fails
        try:
            await message.answer(response)
        except Exception as e:
            # If markdown parse fails, send without formatting
            logger.error(f"Markdown parse error: {e}")
            await bot.send_message(chat_id=message.chat.id, text=response, parse_mode=None)

    except Exception as e:
        logger.error(f"Error handling message: {e}")
        await message.answer("An error occurred while thinking\\. Please try again\\.")

async def main() -> None:
    logger.info("Starting Telegram Bot...")
    # Skip updates on start
    await dp.start_polling(bot, skip_updates=True)

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except (KeyboardInterrupt, SystemExit):
        logger.info("Bot stopped.")
